# Generated by Django 5.0.4 on 2026-03-14 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel_infrastructure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in", models.DateField(db_index=True)),
                ("check_out", models.DateField(db_index=True)),
                ("adults", models.IntegerField(default=1)),
                ("children", models.IntegerField(default=0)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmée"),
                            ("CANCELLED", "Annulée"),
                            ("COMPLETED", "Terminée"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("special_requests", models.TextField(blank=True, default="")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        db_column="hotel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="hotel_infrastructure.hotelmodel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        db_column="room_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="hotel_infrastructure.roommodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="bookings_user_id_1eeb34_idx"
                    ),
                    models.Index(
                        fields=["hotel", "status"], name="bookings_hotel_i_862286_idx"
                    ),
                    models.Index(
                        fields=["room", "status"], name="bookings_room_id_e4aa25_idx"
                    ),
                    models.Index(
                        fields=["check_in", "check_out"],
                        name="bookings_check_i_759ffa_idx",
                    ),
                ],
            },
        ),
    ]
