# Generated by Django 5.0.4 on 2026-03-14 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("stars", models.IntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("INACTIVE", "Inactif"),
                            ("PENDING", "En attente"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=255)),
                ("website", models.URLField(blank=True, default="", max_length=300)),
                ("amenities", models.JSONField(default=list)),
                ("images", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hotels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Simple"),
                            ("DOUBLE", "Double"),
                            ("TWIN", "Twin"),
                            ("SUITE", "Suite"),
                            ("DELUXE", "Deluxe"),
                            ("FAMILY", "Familiale"),
                        ],
                        default="DOUBLE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("capacity", models.IntegerField(default=2)),
                ("size_sqm", models.IntegerField(default=25)),
                ("bed_count", models.IntegerField(default=1)),
                ("bed_type", models.CharField(default="Double", max_length=50)),
                ("floor", models.IntegerField(default=0)),
                ("amenities", models.JSONField(default=list)),
                ("images", models.JSONField(default=list)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotel_infrastructure.hotelmodel",
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["price_per_night"],
            },
        ),
        migrations.AddIndex(
            model_name="hotelmodel",
            index=models.Index(fields=["city"], name="hotels_city_11256f_idx"),
        ),
        migrations.AddIndex(
            model_name="hotelmodel",
            index=models.Index(fields=["status"], name="hotels_status_9c7b12_idx"),
        ),
        migrations.AddIndex(
            model_name="hotelmodel",
            index=models.Index(fields=["stars"], name="hotels_stars_68f33a_idx"),
        ),
        migrations.AddIndex(
            model_name="roommodel",
            index=models.Index(
                fields=["hotel", "is_available"], name="rooms_hotel_i_33a6bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roommodel",
            index=models.Index(fields=["type"], name="rooms_type_5ad055_idx"),
        ),
    ]
