# Generated by Django 5.0.4 on 2026-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="pseudo",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
