# Generated by Django 5.0.4 on 2026-03-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_infrastructure", "0002_usermodel_pseudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
